/**
 * PortalBrandTokensUx  -  Portal Brand Tokens framework v1.0
 *
 * Generates a Next Experience (UX) theme from a Service Portal theme's palette so
 * that Next Experience components embedded in the portal (macroponents such as
 * Product Catalog, Now Assist, AI Search, now-* web components) use the same
 * brand colours and font as the rest of the portal.
 *
 * Why: the UX theme linked in sp_theme.matching_now_experience_theme ships ~5,000
 * component-level colour tokens. They are aliases of ~40 base scales
 * (--now-color--primary-brand-0..20, --now-color--neutral-0..21, ...), which
 * ServiceNow resolves when it writes the page. Regenerating only the base scales
 * from the portal palette re-brands every component.
 *
 * Usage (background script, fix script or the "Sync Next Experience theme" UI action):
 *     var result = new PortalBrandTokensUx().sync('<sp_theme sys_id>');
 *     gs.info(JSON.stringify(result));
 *
 * New client theme (copies the theme with its CSS/JS includes and logo):
 *     var id = new PortalBrandTokensUx().cloneTheme('<template sp_theme sys_id>', 'Acme Theme');
 *
 * Source of truth stays the theme's css_variables. Re-run after every palette change.
 * Records created per portal theme:
 *     sys_ux_theme  "<theme name> (generated UX theme)"
 *     sys_ux_style  "<theme name> - Colors (generated)"
 *     sys_ux_style  "<theme name> - Typography (generated)"
 * The non-colour styles (Shape and Form, Spacing, Motion, ...) are shared with the
 * base UX theme, not copied.
 */
var PortalBrandTokensUx = Class.create();

PortalBrandTokensUx.BASE_UX_THEME = 'fad87d2ca304121029a4d1aed31e610f'; // Coral (UX)
PortalBrandTokensUx.MARKER = 'Generated by PortalBrandTokensUx';

PortalBrandTokensUx.prototype = {
    initialize: function() {
        this.warnings = [];
    },

    /* ------------------------------------------------------------------ */
    /*  Public API                                                         */
    /* ------------------------------------------------------------------ */

    /** Evaluate the theme, (re)write the generated UX theme and link it. */
    sync: function(spThemeId) {
        var spTheme = new GlideRecord('sp_theme');
        if (!spTheme.get(spThemeId))
            throw new Error('sp_theme not found: ' + spThemeId);

        var vars = this.evaluate(spTheme.getValue('css_variables') || '');
        var colours = this.buildBaseColours(vars);
        var font = this._fontFamily(vars);

        var base = this._baseStyles();
        var colorsJson = JSON.parse(base.colors.getValue('style'));
        var replaced = 0;
        for (var k in colours) {
            if (colorsJson.properties.hasOwnProperty(k)) {
                colorsJson.properties[k] = colours[k];
                replaced++;
            }
        }
        var typoJson = JSON.parse(base.typography.getValue('style'));
        var fontsReplaced = 0;
        if (font) {
            for (var t in typoJson.properties) {
                var v = typoJson.properties[t] + '';
                if (/font-family$/.test(t) && v.indexOf('--') !== 0) {
                    typoJson.properties[t] = font;
                    fontsReplaced++;
                }
            }
        }

        var name = spTheme.getValue('name');
        var colorsStyle = this._upsertStyle(name + ' - Colors (generated)', colorsJson);
        var typoStyle = this._upsertStyle(name + ' - Typography (generated)', typoJson);
        var uxTheme = this._upsertTheme(name + ' (generated UX theme)', colorsStyle, typoStyle, base);

        if (spTheme.getValue('matching_now_experience_theme') != uxTheme) {
            spTheme.setValue('matching_now_experience_theme', uxTheme);
        }
        spTheme.setForceUpdate(true); // also flushes the portal's theme CSS cache
        spTheme.update();

        return {
            ux_theme: uxTheme,
            colors_style: colorsStyle,
            typography_style: typoStyle,
            base_tokens_written: replaced,
            font_tokens_written: fontsReplaced,
            warnings: this.warnings
        };
    },

    /**
     * Copy a portal theme with everything "Insert and Stay" leaves behind:
     * CSS includes, JS includes (same order) and the logo/icon images.
     * Returns the new sp_theme sys_id. Rename it before running sync().
     */
    cloneTheme: function(sourceThemeId, newName) {
        var src = new GlideRecord('sp_theme');
        if (!src.get(sourceThemeId))
            throw new Error('sp_theme not found: ' + sourceThemeId);

        var copy = new GlideRecord('sp_theme');
        copy.initialize();
        var els = src.getElements();
        var count = els.size ? els.size() : els.length;
        for (var i = 0; i < count; i++) {
            var el = els.get ? els.get(i) : els[i];
            var field = el.getName() + '';
            if (field.indexOf('sys_') === 0 || field === 'name') continue;
            if (!el.nil()) copy.setValue(field, src.getValue(field));
        }
        copy.setValue('name', newName || 'Copy of ' + src.getValue('name'));
        var id = copy.insert();

        ['m2m_sp_theme_css_include', 'm2m_sp_theme_js_include'].forEach(function(table) {
            var m = new GlideRecord(table);
            m.addQuery('sp_theme', sourceThemeId);
            m.query();
            while (m.next()) {
                var n = new GlideRecord(table);
                n.initialize();
                var mEls = m.getElements();
                var mCount = mEls.size ? mEls.size() : mEls.length;
                for (var j = 0; j < mCount; j++) {
                    var mEl = mEls.get ? mEls.get(j) : mEls[j];
                    var f = mEl.getName() + '';
                    if (f.indexOf('sys_') === 0) continue;
                    n.setValue(f, m.getValue(f));
                }
                n.setValue('sp_theme', id);
                n.insert();
            }
        });

        // image fields (logo, icon) are attachments on ZZ_YYsp_theme
        GlideSysAttachment.copy('ZZ_YYsp_theme', sourceThemeId, 'ZZ_YYsp_theme', id);
        return id;
    },

    /**
     * Evaluate the subset of Sass used in css_variables. Returns a map of
     * variable name -> value, where colours are {r,g,b} objects and anything
     * else is kept as a raw string. Supports: hex, $references, mix(),
     * darken(), lighten(), rgba($c, a), null, !default.
     */
    evaluate: function(scss) {
        var src = (scss + '').replace(/\/\*[\s\S]*?\*\//g, '');
        src = src.split('\n').map(function(line) {
            return line.replace(/(^|[^:"'(])\/\/.*$/, '$1');
        }).join('\n');
        var vars = {};
        var statements = src.split(';');
        for (var i = 0; i < statements.length; i++) {
            var m = statements[i].match(/^\s*(\$[\w-]+)\s*:\s*([\s\S]*?)\s*$/);
            if (!m) continue;
            var name = m[1], raw = m[2], isDefault = /!default\s*$/.test(raw);
            raw = raw.replace(/\s*!default\s*$/, '');
            if (isDefault && vars.hasOwnProperty(name) && vars[name] !== null) continue;
            vars[name] = this._value(raw, vars);
        }
        return vars;
    },

    /** Map the evaluated portal tokens onto the Next Experience base scales. */
    buildBaseColours: function(v) {
        var self = this, out = {};
        var W = { r: 255, g: 255, b: 255 }, K = { r: 0, g: 0, b: 0 };
        function c(name, fallback) {
            var x = v[name];
            if (x && typeof x === 'object') return x;
            if (fallback) return c(fallback);
            self.warnings.push('Missing colour ' + name);
            return { r: 128, g: 128, b: 128 };
        }
        function put(k, col) { out[k] = self._rgb(col); }
        function mix(a, b, w) { return self._mix(a, b, w); }
        function brandScale(prefix, base) {
            for (var i = 0; i <= 20; i++) {
                if (i < 10) put(prefix + i, mix(W, base, (10 - i) * 0.09));
                else if (i === 10) put(prefix + i, base);
                else put(prefix + i, mix(K, base, (i - 10) * 0.063));
            }
        }
        function alertScale(prefix, base, light, dark) {
            put(prefix + '0', light);
            put(prefix + '1', mix(W, base, 0.5));
            put(prefix + '2', base);
            put(prefix + '3', dark);
            put(prefix + '4', mix(K, base, 0.45));
            put(prefix + '5', mix(K, base, 0.75));
        }

        var primary = c('$ui-primary', '$palette-primary');
        var accent = c('$ui-selected', '$palette-accent');
        var link = c('$ui-link', '$palette-secondary');
        var focus = c('$ui-focus', '$palette-focus');

        // brand scales
        brandScale('--now-color--primary-brand-', primary);
        brandScale('--now-color--secondary-brand-', accent);
        brandScale('--now-color--supplementary1-brand-', link);

        // short scales
        put('--now-color--primary-0', c('$palette-primary-lightest'));
        put('--now-color--primary-1', primary);
        put('--now-color--primary-2', c('$palette-primary-dark'));
        put('--now-color--primary-3', c('$palette-primary-darkest'));
        put('--now-color--secondary-0', c('$palette-primary-lightest'));
        put('--now-color--secondary-1', c('$palette-primary-dark'));
        put('--now-color--secondary-2', mix(K, primary, 0.5));
        put('--now-color--secondary-3', c('$palette-primary-darkest'));
        put('--now-color--interactive-0', c('$palette-primary-lightest'));
        put('--now-color--interactive-1', c('$palette-primary-light'));
        put('--now-color--interactive-2', primary);
        put('--now-color--interactive-3', c('$palette-primary-dark'));
        put('--now-color--interactive-4', c('$palette-primary-darkest'));
        put('--now-color--link-1', mix(W, link, 0.35));
        put('--now-color--link-2', link);
        put('--now-color--link-3', c('$ui-link-hover'));
        put('--now-color--link-4', mix(K, link, 0.63));
        put('--now-color--focus-1', mix(W, focus, 0.35));
        put('--now-color--focus-2', focus);
        put('--now-color--focus-3', mix(K, focus, 0.65));
        put('--now-color_selection--primary-0', c('$ui-selected-subtle'));
        put('--now-color_selection--primary-1', c('$palette-accent-light'));
        put('--now-color_selection--primary-2', accent);
        put('--now-color_selection--primary-3', c('$ui-selected-strong'));
        put('--now-color_selection--primary-4', mix(K, accent, 0.5));
        put('--now-color_selection--secondary-0', c('$palette-primary-lightest'));
        put('--now-color_selection--secondary-1', c('$palette-primary-light'));
        put('--now-color_selection--secondary-2', primary);
        put('--now-color_selection--secondary-3', c('$palette-primary-dark'));
        put('--now-color_selection--secondary-4', c('$palette-primary-darkest'));
        put('--now-color_brand--primary', c('$palette-primary-darkest'));
        put('--now-color_brand--secondary', c('$palette-primary-dark'));
        put('--now-color_brand--neutral', c('$palette-neutral-85'));
        for (var s = 1; s <= 6; s++) put('--now-color_surface--brand-' + s, mix(W, primary, 1 - s * 0.05));

        // neutrals: 0..21 follow the palette stops; the "less" / "mid" / surface
        // variants are interpolated along the same ramp
        var stops = [W, c('$palette-neutral-5'), c('$palette-neutral-10'), c('$palette-neutral-20'),
            c('$palette-neutral-30'), c('$palette-neutral-40'), c('$palette-neutral-50'),
            mix(c('$palette-neutral-50'), c('$palette-neutral-60'), 0.5), c('$palette-neutral-60'),
            c('$palette-neutral-70'), c('$palette-neutral-80'),
            mix(c('$palette-neutral-80'), c('$palette-neutral-85'), 0.5), c('$palette-neutral-85'),
            mix(c('$palette-neutral-85'), c('$palette-neutral-90'), 0.5), c('$palette-neutral-90'),
            mix(c('$palette-neutral-90'), c('$palette-neutral-95'), 0.5), c('$palette-neutral-95'),
            mix(c('$palette-neutral-95'), c('$palette-neutral-100'), 0.5), c('$palette-neutral-100'),
            mix(c('$palette-black'), c('$palette-neutral-100'), 0.3),
            mix(c('$palette-black'), c('$palette-neutral-100'), 0.6), c('$palette-black')];
        for (var n = 0; n <= 21; n++) put('--now-color--neutral-' + n, stops[n]);
        function ramp(t) { // t in [0, 21]
            var lo = Math.floor(t), hi = Math.min(21, lo + 1), f = t - lo;
            return mix(stops[hi], stops[lo], f);
        }
        for (var j = 0; j <= 20; j++) {
            put('--now-color--neutral-less-' + j, ramp(0.6 + j * 0.84));
            put('--now-color--neutral-mid-' + j, ramp(0.8 + j * 0.86));
        }
        for (var b = 1; b <= 9; b++) put('--now-color_background--neutral-' + b, ramp(b * 0.11));
        for (var u = 1; u <= 6; u++) {
            put('--now-color_surface--neutral-' + u, ramp(u * 0.5));
            put('--now-color_surface--divider-' + u, ramp(1 + u * 1.2));
        }

        // status
        alertScale('--now-color_alert--positive-', c('$ui-success'), c('$ui-success-bg'), c('$palette-success-dark'));
        alertScale('--now-color_alert--critical-', c('$ui-danger'), c('$ui-danger-bg'), c('$palette-danger-dark'));
        alertScale('--now-color_alert--warning-', c('$ui-warning'), c('$ui-warning-bg'), c('$palette-warning-dark'));
        alertScale('--now-color_alert--info-', c('$ui-info'), c('$ui-info-bg'), c('$palette-info-dark'));
        return out;
    },

    /* ------------------------------------------------------------------ */
    /*  Sass-subset evaluation                                             */
    /* ------------------------------------------------------------------ */

    _value: function(raw, vars) {
        raw = (raw + '').trim();
        if (raw === 'null' || raw === '') return null;
        var col = this._colour(raw, vars);
        return col !== undefined ? col : raw;
    },

    /** Returns {r,g,b}, null for null-ish, or undefined when not a colour. */
    _colour: function(expr, vars) {
        expr = (expr + '').trim();
        var m;
        if (/^#[0-9a-f]{3}$/i.test(expr)) {
            return { r: parseInt(expr.charAt(1) + expr.charAt(1), 16), g: parseInt(expr.charAt(2) + expr.charAt(2), 16), b: parseInt(expr.charAt(3) + expr.charAt(3), 16) };
        }
        if (/^#[0-9a-f]{6}$/i.test(expr)) {
            return { r: parseInt(expr.substr(1, 2), 16), g: parseInt(expr.substr(3, 2), 16), b: parseInt(expr.substr(5, 2), 16) };
        }
        if (/^(white)$/i.test(expr)) return { r: 255, g: 255, b: 255 };
        if (/^(black)$/i.test(expr)) return { r: 0, g: 0, b: 0 };
        if (/^\$[\w-]+$/.test(expr)) {
            var ref = vars[expr];
            return (ref && typeof ref === 'object') ? ref : undefined;
        }
        if ((m = expr.match(/^mix\((.*)\)$/i))) {
            var a = this._args(m[1]);
            if (a.length < 2) return undefined;
            var c1 = this._colour(a[0], vars), c2 = this._colour(a[1], vars);
            var w = a.length > 2 ? parseFloat(a[2]) / 100 : 0.5;
            return (c1 && c2) ? this._mix(c1, c2, w) : undefined;
        }
        if ((m = expr.match(/^(darken|lighten)\((.*)\)$/i))) {
            var d = this._args(m[2]), base = this._colour(d[0], vars);
            if (!base) return undefined;
            var amt = parseFloat(d[1]) / 100 * (m[1].toLowerCase() === 'darken' ? -1 : 1);
            var hsl = this._toHsl(base);
            hsl.l = Math.max(0, Math.min(1, hsl.l + amt));
            return this._fromHsl(hsl);
        }
        if ((m = expr.match(/^rgba\((.*)\)$/i))) {
            var r = this._args(m[1]);
            if (r.length === 2) return this._colour(r[0], vars);
            if (r.length >= 3) return { r: +r[0], g: +r[1], b: +r[2] };
        }
        return undefined;
    },

    _args: function(s) {
        var out = [], depth = 0, cur = '';
        for (var i = 0; i < s.length; i++) {
            var ch = s.charAt(i);
            if (ch === '(') depth++;
            if (ch === ')') depth--;
            if (ch === ',' && depth === 0) { out.push(cur.trim()); cur = ''; continue; }
            cur += ch;
        }
        if (cur.trim()) out.push(cur.trim());
        return out;
    },

    _mix: function(c1, c2, w) { // Sass mix(): weight w of c1
        return {
            r: Math.round(c1.r * w + c2.r * (1 - w)),
            g: Math.round(c1.g * w + c2.g * (1 - w)),
            b: Math.round(c1.b * w + c2.b * (1 - w))
        };
    },

    _toHsl: function(c) {
        var r = c.r / 255, g = c.g / 255, b = c.b / 255;
        var mx = Math.max(r, g, b), mn = Math.min(r, g, b), l = (mx + mn) / 2, h = 0, s = 0, d = mx - mn;
        if (d) {
            s = l > 0.5 ? d / (2 - mx - mn) : d / (mx + mn);
            if (mx === r) h = (g - b) / d + (g < b ? 6 : 0);
            else if (mx === g) h = (b - r) / d + 2;
            else h = (r - g) / d + 4;
            h /= 6;
        }
        return { h: h, s: s, l: l };
    },

    _fromHsl: function(hsl) {
        function hue(p, q, t) {
            if (t < 0) t += 1;
            if (t > 1) t -= 1;
            if (t < 1 / 6) return p + (q - p) * 6 * t;
            if (t < 1 / 2) return q;
            if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
            return p;
        }
        var r, g, b;
        if (!hsl.s) { r = g = b = hsl.l; } else {
            var q = hsl.l < 0.5 ? hsl.l * (1 + hsl.s) : hsl.l + hsl.s - hsl.l * hsl.s, p = 2 * hsl.l - q;
            r = hue(p, q, hsl.h + 1 / 3); g = hue(p, q, hsl.h); b = hue(p, q, hsl.h - 1 / 3);
        }
        return { r: Math.round(r * 255), g: Math.round(g * 255), b: Math.round(b * 255) };
    },

    _rgb: function(c) { return c.r + ',' + c.g + ',' + c.b; },

    _fontFamily: function(vars) {
        var f = vars['$ui-font-family'];
        return (typeof f === 'string' && f) ? f : null;
    },

    /* ------------------------------------------------------------------ */
    /*  Records                                                            */
    /* ------------------------------------------------------------------ */

    _baseStyles: function() {
        var res = { colors: null, typography: null, others: [] };
        var m = new GlideRecord('m2m_theme_style');
        m.addQuery('theme', PortalBrandTokensUx.BASE_UX_THEME);
        m.query();
        while (m.next()) {
            var st = m.style.getRefRecord();
            var name = st.getValue('name');
            var type = st.getValue('type');
            if (type === 'variant') continue; // dark mode is not supported by the portal theme
            if (name === 'Colors') res.colors = st;
            else if (name === 'Typography') res.typography = st;
            else res.others.push({ style: st.getUniqueValue(), order: m.getValue('order') });
        }
        if (!res.colors || !res.typography)
            throw new Error('Base UX theme is missing its Colors or Typography style');
        return res;
    },

    _upsertStyle: function(name, json) {
        var st = new GlideRecord('sys_ux_style');
        st.addQuery('name', name);
        st.query();
        if (!st.next()) {
            st.initialize();
            st.setValue('name', name);
            st.setValue('type', 'core');
        }
        st.setValue('style', JSON.stringify(json));
        return st.isNewRecord() ? st.insert() : (st.update(), st.getUniqueValue());
    },

    _upsertTheme: function(name, colorsStyle, typoStyle, base) {
        var th = new GlideRecord('sys_ux_theme');
        th.addQuery('name', name);
        th.query();
        if (!th.next()) {
            th.initialize();
            th.setValue('name', name);
            th.setValue('active', true);
        }
        th.setValue('description', PortalBrandTokensUx.MARKER + '. Do not edit - change the portal theme palette and re-run the sync.');
        var id = th.isNewRecord() ? th.insert() : (th.update(), th.getUniqueValue());

        var wanted = {};
        wanted[colorsStyle] = 0;
        wanted[typoStyle] = 0;
        base.others.forEach(function(o) { wanted[o.style] = o.order || 0; });
        var existing = {};
        var m = new GlideRecord('m2m_theme_style');
        m.addQuery('theme', id);
        m.query();
        while (m.next()) {
            var s = m.getValue('style');
            if (!wanted.hasOwnProperty(s)) m.deleteRecord();
            else existing[s] = true;
        }
        for (var sid in wanted) {
            if (existing[sid]) continue;
            var n = new GlideRecord('m2m_theme_style');
            n.initialize();
            n.setValue('theme', id);
            n.setValue('style', sid);
            n.setValue('order', wanted[sid]);
            n.insert();
        }
        return id;
    },

    type: 'PortalBrandTokensUx'
};
