"""Turn WOFF2 files into a portal stylesheet with embedded @font-face rules.

    python tools/embed_font.py "Arvo" 400=examples/aareal/fonts/arvo-400.woff2 700=examples/aareal/fonts/arvo-700.woff2 > aareal-fonts.scss

Paste the output into a new sp_css record, add it to the client theme as a CSS
include with a low order (e.g. 95), then set $ui-font-family or
$ui-font-family-heading in Section 1d and click "Sync Next Experience theme".
Embedding keeps the portal free of runtime requests to font CDNs (CSP, GDPR).
Only embed fonts whose licence allows it (e.g. SIL OFL) and keep the notice.
"""
import base64
import sys


def main(argv):
    if len(argv) < 2:
        sys.exit(__doc__)
    family, faces = argv[0], argv[1:]
    out = ["// @font-face rules for '%s' generated by tools/embed_font.py" % family]
    for spec in faces:
        weight, _, path = spec.partition("=")
        data = base64.b64encode(open(path, "rb").read()).decode()
        style = "italic" if weight.endswith("i") else "normal"
        out.append("@font-face {\n  font-family: '%s';\n  font-style: %s;\n  font-weight: %s;\n  font-display: swap;\n"
                   "  src: url(data:font/woff2;base64,%s) format('woff2');\n}" % (family, style, weight.rstrip("i"), data))
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main(sys.argv[1:])
